name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }}
      HOGE: ${{ secrets.HOGE }}
    steps:
      - run: echo "${PASSWORD}"
      - run: echo "${HOGE}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"

